[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opengeocity-web"
version = "1.0.0"
description = "OpenGeoCity Web Frontend"
requires-python = ">=3.12"
dependencies = [
    "Flask>=3.1.2",
    "flask-cors>=6.0.2"
]

